---
before_script: bundle exec rake db:create db:schema:load
bundler_args: --without assets:development:production
cache: bundler
script:
  - bundle exec rake
  - bundle exec rubocop --rails --fail-level=refactor
language: ruby
rvm:
  - 2.1.2
