development:
  adapter: postgresql
  database: adopt_a_hydrant_development
  username: postgres
  password:

test:
  adapter: postgresql
  database: adopt_a_hydrant_test
  username: postgres
  password:
